vary_parameters_range:
    # <parameter_name:>
    #   range: [<lower value>,<upper value>] 
    infection_rate:
        range: [0.0035, 0.14]
    mortality_period:
        range: [4.0, 16.0]
    recovery_period:
        range: [4.0, 16.0]
    mild_recovery_period:
        range: [4.5, 12.5]
    incubation_period:
        range: [2.0, 6.0]
    period_to_hospitalisation:
        range: [8.0, 16.0]
    immunity_duration:
        range: [100.0, 300.0]
    population:
        range: [100000, 500000]
    pop_mu:
        range: [20.0, 30.0]
    pop_sigma:
        range: [5.0, 15.0]
    infection_rate_alpha:
        range: [0.0035, 0.2]
    infection_rate_beta:
        range: [0.0035, 0.2]

# selected_vary_parameters: ["mortality_period",
#                            "recovery_period",
#                            "mild_recovery_period",
#                           ]

# selected_vary_parameters: ["infection_rate",
#                            "incubation_period",
#                            "period_to_hospitalisation",
#                           ]

selected_vary_parameters: ["infection_rate",
                           "infection_rate_alpha",
                           "infection_rate_beta",
                          ]


# selected_vary_parameters: ["infection_rate",
#                            "incubation_period",
#                            "mild_recovery_period",
#                            "immunity_duration",
#                           ]

# selected_vary_parameters: [ "population",
#                             "pop_mu",
#                             "pop_sigma"
#                             ]

distribution_type: "Uniform" # Uniform, DiscreteUniform

polynomial_order: 3

decoder_output_column: "num hospitalisations today"

#   ---------------------------------------------------------------
# sampler_name: str
#   Samplers in the context of EasyVVUQ are classes that generate
#   sequences of parameter dictionaries.
#   available sampler: [SCSampler,PCESampler]
#
#   SCSampler: Stochastic Collocation sampler
#   PCESampler : Polynomial Chaos Expansion
#   ---------------------------------------------------------------
sampler_name: "SCSampler"


# quadrature_rule : char
#     The quadrature method, default is Gaussian "G".
#     "G" -> Gaussian , "C" -> Clenshaw_Curtis
quadrature_rule: "G"

# ------- NOTE ------------
# if you set quadrature_rule="C", then you need to make sure
#     sparse=True
#     growth=True
#     midpoint_level1=True


# sparse : bool
#             If True use sparse grid instead of normal tensor product grid,
#             default is False
sparse: False

# growth: bool
#     Sets the growth rule to exponential for Clenshaw Curtis quadrature,
#     which makes it nested, and therefore more efficient for sparse grids.
#     Default is False.
growth: False

# midpoint_level1: bool,  ----- ONLY FOR SCSampler ------
#     determines how many points the 1st level of a sparse grid will have.
#     If midpoint_level1 = True, order 0 quadrature will be generated
midpoint_level1: False

# dimension_adaptive: bool, ----- ONLY FOR SCSampler ------
#     determines wether to use an insotropic sparse grid, or to adapt
#     the levels in the sparse grid based on a hierachical error measure
dimension_adaptive: False

# regression: bool, ----- ONLY FOR PCESampler ------
#    If True, regression variante (point collecation) will be used,
#    otherwise projection variante (pseud-spectral) will be used.
#    Default value is False.
regression: False

